### PR TITLE
Maven POM changes

### PR DESCRIPTION
**Pull request by rea-al-zz**
Download or provide a wlp to configure the sample in a server.

### CODE REVIEW

**Comment by rea-al-zz** [comment]
Hi guys, this pull request was reviewed by @cbridgha

**Comment by katheris** [comment]
This looks similar to the functionality that I have added to the sample.microservices.12factorapp repository. You can use the liberty-maven plugin and the install goal to install Liberty, might be a nicer way to do it since the plugin already exists?

**Comment by rea-al-zz** [comment]
Yes, it's almost the same but this can use the two zips on the DHE maven repo that make it easier to download and install due that it does not require license acceptance. I think that it could be a better way to download the server.

**Comment by cbridgha** [comment]
Hi - I asked Alexis to help integrate the newly available freemium zips that are now available on DHE maven repo.  These don't require adding the license to the pom, and will essentially unzip to the specified location.    The Liberty plugin can still be used if a specific feature needs to be added to these base editions...   But Most of these examples use the webprofile level...  Its just a convenience.

**Comment by katheris** [comment]
Oh ok, that's useful that you don't need to provide the license. I guess my main question would be why are we not adding this to the liberty-maven plugin, it looks like a lot of code to be adding every time we want to use this, whereas we could make it nicer for the end user to implement if we had it as a goal in the liberty-maven plugin.

**Comment by ebullient** [comment]
Can we split this pull request? I think we have a separate bit (which I would like to accept) that fixes the dependency on the application..

**Comment by rea-al-zz** [comment]
Sure, let me update my branch with the changes, or do you prefer a new pull request when it's finished?

**Comment by ebullient** [comment]
Would like two pull requests (this one, where we figure out how to download wlp when it is missing), and a separate one (to fix the dependency between wlpcfg and the application). I can accept the latter immediately. I think we have some work to do between you and Kate on the former.

**Pull request closed without merging**
